### ISSUE TITLE
Marlin Firmware - #error "LEVEL_CORNERS_INSET is now LEVEL_CORNERS_INSET_LFRB . Please update your Configuration.h

### ISSUE THREAD

**Issue by aidanaedy** [pessimism/TronxyX1#1]
I have tried to compile several versions of the marlin Tronxy X1 firmware whilst adding in your configuration.h and the configuration_adv.h files, but I get errors that it cannot compile as it is an out of date file. what versions does it work with.

Sorry, I cannot find an email address for you. My email is aidanaedy@gmail.com

Regards,
Aidan Aedy

**Comment by pessimism** [comment]
Hello, the last version I tested the config with was Marlin 2.0.1.  If you use my config you will need to change the extruder steps/mm in configuration.h line 721 for the stock extruder back to 100, mine is changed because I replaced the extruder on my X1 with a different model

**Comment by pessimism** [comment]
I've updated the config for Marlin 2.0.5.3
If you are using stock hardware you will now also need to change #define TEMP_SENSOR_0 5 from 5 back to 11 as I have changed hotend and thermistor on mine
